server:
  port: ${random.int[10000,19999]}

eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    home-page-url-path: /
    # docker 部署开启
  #        prefer-ip-address: true
  #        ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://172.19.10.238:8761/eureka
      # docker 部署开启
      # defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

spring:
  application:
    name: electric-service
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port:  ${RABBIT_MQ_PORT:5672}
    username: guest
    password: guest
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  cloud:
    consul:
      enabled: true
      host: 127.0.0.1
      port: 8500
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        register: true
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000